packaging_format = 2

id = "munin"
name = "Munin"
description.en = "Resource monitoring tool"
description.fr = "Outil de supervision de ressources"

version = "2.0.75~ynh1"

maintainers = []

[upstream]

license = "GPL-2.0-only"
website = "https://munin-monitoring.org/"
demo = "https://demo.example.com"
admindoc = "https://guide.munin-monitoring.org/en/latest/index.html"
userdoc = "https://yunohost.org/apps"
code = "https://github.com/munin-monitoring/munin"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/munin"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.system_user]

    #[resources.install_dir]

    [resources.permissions]
    main.url = "/"

    #[resources.ports]

    [resources.apt]
    packages = "munin, munin-node"
