#!/bin/bash

# Retrieve arguments
domain=$1
path=$2

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a munin
if [[ ! $? -eq 0 ]]; then
    echo "Error : $domain$path is not available"
    exit 1
fi

sudo apt-get update
# those are dependencies to munin plugins that can be auto-configured
sudo apt-get install smartmontools libcache-cache-perl -y
# now really install munin
sudo apt-get install munin fcgiwrap -y
sudo service munin restart
sudo service munin-node restart

sed -i "s@YNH_DOMAIN@$(cat /etc/yunohost/current_host)@g" ../conf/munin.conf
sudo cp ../conf/munin.conf /etc/munin/munin.conf

sed -i "s@YNH_DOMAIN@$(cat /etc/yunohost/current_host)@g" ../conf/munin-node.conf
sudo cp ../conf/munin-node.conf /etc/munin/munin-node.conf


# we run the fastcgi process as www-data
sudo chown www-data:adm /var/log/munin/munin-cgi-{graph,html}.log
# strangely debian install those files with +x permissions
sudo chmod -x /var/log/munin/munin-cgi-{graph,html}.log

sudo cp ../conf/munin-fastcgi.init /etc/init.d/munin-fastcgi
sudo chmod +x /etc/init.d/munin-fastcgi
sudo update-rc.d munin-fastcgi defaults

# trigger generation of html pages asap
sudo su -c /usr/bin/munin-cron munin

# the cgi graph tool fails if this dir does not exists...
mkdir -p /var/lib/munin/cgi-tmp/munin-cgi-graph/$(cat /etc/yunohost/current_host)/yunohost.$(cat /etc/yunohost/current_host)
# ...and is not owned by www-data
sudo chown www-data:munin /var/lib/munin/cgi-tmp

echo "Nginx configuration..."
sed -i "s@YNH_LOCATION@$path@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/munin.conf


# configure the munin node
rm  /etc/munin/plugins/exim_mailstats

sudo service munin-fastcgi restart
sudo service munin-node restart
sudo yunohost service add munin -l /var/log/munin/munin.log
sudo service nginx reload
sudo yunohost app ssowatconf
