#!/bin/bash

domain=$(sudo yunohost app setting munin domain)

sudo rm /etc/nginx/conf.d/$domain.d/munin.conf

sudo update-rc.d munin-fastcgi remove
sudo yunohost service remove munin

sudo yunohost app ssowatconf
sudo service nginx reload
