#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template="munin-fastcgi.init" --destination="/etc/init.d/munin-fastcgi"

ynh_config_add --template="munin-node.conf" --destination="/etc/munin/munin-node.conf"

ynh_config_add --template="munin.conf" --destination="/etc/munin/munin.conf"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

yunohost service add "$app" --description="A short description of the app" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

# configure the munin node
if [[ -f /etc/munin/plugins/exim_mailstats ]]; then
  ynh_safe_rm  /etc/munin/plugins/exim_mailstats
fi

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app-fastcgi" --action="start"

ynh_systemctl --service="$app-node" --action="start"

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
