#!/bin/bash

# Retrieve arguments
domain=$(sudo yunohost app setting munin domain)
path=$(sudo yunohost app setting munin path)
path=${path%/}

sed -i "s@YNH_LOCATION@$path@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/munin.conf

sudo service nginx reload
sudo yunohost app ssowatconf

